# Generated by Django 5.1.4 on 2025-02-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentreport',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
